# Generated by Django 4.1.3 on 2022-11-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_ingredients_menu_item_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='ingredients',
            field=models.ManyToManyField(to='menu_app.ingredients'),
        ),
    ]
