# Generated by Django 4.1.3 on 2022-11-14 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_alter_menu_item_category_alter_menu_item_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items_by_categories', to='menu_app.category'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_by_cuisines', to='menu_app.cuisine'),
        ),
    ]
